# -*- coding: utf-8 -*-
"""chat_client.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLx7G6NmBCz-5kclCQP52XAL8IFfuRhW
"""

import socket
import threading

def receive_messages(sock):
    while True:
        try:
            msg = sock.recv(1024).decode('utf-8')
            if msg:
                print(msg)
        except Exception as e:
            print(f"Exception: {e}")
            break

def start_client():
    host = "127.0.0.1"
    port = 12345

    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        client_socket.connect((host, port))
        print(f"[*] Connected to {host}:{port}")

        receive_thread = threading.Thread(target=receive_messages, args=(client_socket,))
        receive_thread.start()

        while True:
            msg = input("")
            if msg.lower() == "exit":
                break
            client_socket.send(msg.encode('utf-8'))

        client_socket.close()
    except Exception as e:
        print(f"Exception: {e}")

if __name__ == "__main__":
    start_client()